bot: {automerge: true}
conda_forge_output_validation: true
build_with_mambabuild: false
test: native_and_emulated
build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
  osx_arm64: osx_64
